### ISSUE TITLE
cat command is breaking the package on windows

### ISSUE THREAD

**Issue by OmarAbdo** [acordiner92/npm-audit-pipeline#151]
Hi, 

I was trying to use your package on a windows machine and it always throws this error 

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\skp\code\boilerplate\node_modules\npm-audit-pipeline\executor.js:16:41
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest-boilerplate@0.0.1 package-audit: `npm-audit --low=4 --moderate=3 --high=2 --critical=1`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nest-boilerplate@0.0.1 package-audit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\7369\AppData\Roaming\npm-cache\_logs\2021-03-30T19_12_44_229Z-debug.log
```
When I checked the code I doubted the cat flag after the | in executor.js line 11 and when I removed it and the |, it worked perfectly. 

```javascript
const callNpm = async (retry, retries) =>
    new Promise((resolve, reject) => {
      exec('npm audit --json | cat', (error, stdOut) => {
        const parsedStdOut = jsonParser.parse(stdOut);
        if (error || parsedStdOut.error) {
          if (exceededRetries(retry, retries)) {
            logger.error(`Failed to fetch NPM audit after ${retry} retries`);
            return reject(parsedStdOut.error || error);
          }
          return resolve(callNpm(retry, retries + 1));
        }
        return resolve(parsedStdOut);
      });
    });
```
Can you please make this fix official? thank you in advance!

**Comment by acordiner92** [comment]
Hey, @OmarAbdo thanks for raising this issue. Sorry for not getting back to you sooner. I've now gotten a bit of time to work on this library so I'll be looking to get a fix in for this issue. If I understand correctly from what you said removing the `| cat` fixed the problem on windows? e.g
`
exec('npm audit --json', (error, stdOut) => {......
`

**Comment by acordiner92** [comment]
Awesome, thanks for the clarification

**Comment by acordiner92** [comment]
Hey, @OmarAbdo I have pushed out version 0.6.0 out of the library which addresses the window's issue. I have run it against window's server https://github.com/acordiner92/npm-audit-pipeline/runs/3389637603?check_suite_focus=true and it runs fine. I'll be closing out this ticket now. Let me know if you run into any more issues. Thanks
