### ISSUE TITLE
Failed to fetch NPM audit after 3 retries Error: Command failed: npm audit --json

### ISSUE THREAD

**Issue by RobinZergiebel** [acordiner92/npm-audit-pipeline#62]
Hey,

I'm always getting this error now when running the audit scan.
I have a working internet connection and "npm audit --json" works fine.
Any fix for this?

Cheers,
Robin

**Comment by acordiner92** [comment]
Hey mate, sorry didn't see this til today. What version of node are you using? I noticed I think from node 11+ the error shows, from what I could see it looks to be around node child process logic changing. I'm going to push a fix out for it to get to work on all versions of node from 8+ 
Hopefully have something by end of the week

**Comment by acordiner92** [comment]
Okay it appears to be find regardless of the node version from testing so I was wrong about that, but it does fail if I use yarn to setup the Javascript project. I'll look into why yarn does not work. I would suggest for the time being to use npm if you can

**Comment by acordiner92** [comment]
Okay I found the issue through replicating it on our company node project and have pushed out a fix for it. Please try the latest version 0.4.3 and let me know how it goes

**Comment by RobCoPKC** [comment]
Hey,

my node version is 12.14.0. I just updated to 0.4.3 and now run into another problem:

`> my-app@1.0.1 package-audit C:\Data\workspaces\my-app
> npm-audit

undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\Data\workspaces\my-app\node_modules\npm-audit-pipeline\executor.js:12:41
    at ChildProcess.exithandler (child_process.js:302:5)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@1.0.1 package-audit: `npm-audit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@1.0.1 package-audit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by acordiner92** [comment]
@RobCoPKC Hey, I can't replicate the error your having there unfortunately. Would you be able to setup a basic repository with the failing example above, to help me diagnose the issue?

**Comment by RobCoPKC** [comment]
Hey,

sorry for the late response, I was kinda busy...
I have added you as a collaborator to my test project.

Cheers,
Robin

**Comment by fh-cmays** [comment]
I can confirm the same issue node 12.18.2:

`npm run package-audit

 

> crm@0.0.0 package-audit
> npm-audit --low=4 --moderate=3 --high=0 --critical=0 --retry=3

 

undefined:1

 

 

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\Users\xxxx\Desktop\Code\crm\node_modules\npm-audit-pipeline\executor.js:12:41
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm ERR! code 1
npm ERR! path C:\Users\xxx\Desktop\Code\crm
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm-audit --low=4 --moderate=3 --high=0 --critical=0 --retry=3

 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xx\AppData\Local\npm-cache\_logs\2021-02-09T15_04_47_720Z-debug.log`

**Comment by acordiner92** [comment]
Hey guys apologies for not responding in a while. I've been a bit busy with work but got some time to work on this library so I'll be looking into addressing these node version issues. I believe there was an API change for child processes in the later versions of the node which is probably causing this problem. I'll let you guys know when I got a new release out with these fixes.

**Comment by acordiner92** [comment]
Hey, @RobinZergiebel @fh-cmays I have pushed out a new version 0.6.0 which fixes newer versions of Node so please upgrade to that. I also noticed from @fh-cmays's error, it shows it is from a window environment. I have also added an additional fix as brought up in this issue https://github.com/acordiner92/npm-audit-pipeline/issues/151 that causes the library to error out on window environments. I'll be closing this ticket out now. Let me know if you have any further issues. Thanks
